version: '3.10'

services:
  # PostgreSQL 数据库服务
  db:
    image: postgres:14-alpine  # 使用14版本，与您的数据兼容
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=memoq_ticket_system 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 缓存服务
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django 后端服务（开发模式）
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app  # 挂载源代码
      - backend_venv:/app/.venv  # 保留虚拟环境
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=memoq_ticket_system.settings
    command: >
      sh -c ". .venv/bin/activate && 
              pip install -r requirements.txt &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Vue.js 前端服务（开发模式）
  frontend:
    build:
      context: ./frontend/memoq-ticket-frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/memoq-ticket-frontend:/app  # 挂载源代码
      - /app/node_modules  # 避免覆盖node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # 确保文件监视正常工作
      - WDS_SOCKET_PORT=0  # 解决WebSocket连接问题
    depends_on:
      - backend
    command: npm run dev  # 使用开发服务器

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
  backend_venv: